name: CI

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./front
      run: npm install

    - name: Run unit tests
      working-directory: ./front
      run: npm run test:unit

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        working-directory: front
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:5173'

  build-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t streamer-base .

    - name: Test Docker image
      run: |
        docker run --name test-container -d streamer-base
        docker ps | grep -q test-container
        docker stop test-container